package net.ximatai.muyun.fileserver.common.exception.mapper;

import jakarta.annotation.Priority;
import jakarta.inject.Inject;
import jakarta.ws.rs.Priorities;
import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.ext.ExceptionMapper;
import jakarta.ws.rs.ext.Provider;
import net.ximatai.muyun.fileserver.api.dto.ErrorResponse;
import net.ximatai.muyun.fileserver.common.context.RequestContextHolder;
import net.ximatai.muyun.fileserver.common.context.RequestMetadata;
import net.ximatai.muyun.fileserver.common.context.RequestMetadataHolder;
import org.jboss.logging.Logger;

/**
 * WebApplicationException represents an intentional HTTP response, including
 * the 404 generated by the REST runtime when no resource matches a request.
 */
@Provider
@Priority(Priorities.USER)
public class WebApplicationExceptionMapper implements ExceptionMapper<WebApplicationException> {

    private static final Logger LOG = Logger.getLogger(WebApplicationExceptionMapper.class);

    @Inject
    RequestMetadataHolder requestMetadataHolder;

    @Inject
    RequestContextHolder requestContextHolder;

    @Override
    public Response toResponse(WebApplicationException exception) {
        Response response = exception.getResponse();
        if (response == null) {
            // Defensive only: JAX-RS constructors normally always provide a response.
            return Response.serverError().build();
        }

        int status = response.getStatus();
        if (status < 500) {
            if (status >= 400) {
                logClientError(status);
            }
            // Returning the framework response intact preserves status, headers and entity.
            return response;
        }

        LOG.error("request failed with server web application exception", exception);
        return serverError(status);
    }

    private void logClientError(int status) {
        if (!LOG.isDebugEnabled()) {
            return;
        }
        RequestMetadata request = requestMetadataHolder.get();
        LOG.debugf("expected client error: method=%s, path=%s, status=%d, traceId=%s",
                request == null ? null : request.method(),
                request == null ? null : request.path(),
                status,
                request == null ? null : request.traceId());
    }

    private Response serverError(int status) {
        try {
            return Response.status(status)
                    .type(MediaType.APPLICATION_JSON_TYPE)
                    .entity(new ErrorResponse("internal server error", requestId()))
                    .build();
        } catch (RuntimeException ignored) {
            return Response.status(status).build();
        }
    }

    private String requestId() {
        try {
            return requestContextHolder.getRequired().requestId();
        } catch (IllegalStateException ignored) {
            RequestMetadata metadata = requestMetadataHolder.get();
            return metadata == null ? null : metadata.traceId();
        }
    }
}
